BATCH_SIZE = 32
LOSS = ""
LEARNING_RATE = 0.001
NO_EPOCHS = 50
DROPOUT = False
OPTIMIZER = "adam"
MODEL_FORMAT = ""
MODEL_NAME = 'rn18'
ATTACK_TYPE = 'printing'

INFERENCE_DEVICE = 'CUDA'
TRAINING_DEVICE = 'CUDA'

TRAIN_DATASET = 'CVPR23'
TEST_DATASET = 'HAND_CRAWL'

PATH_TO_IMAGES = ''
PATH_TO_VIDEOS = ''
PATH_TO_SINGLE_VIDEO = ''
PATH_TO_DATASET = '/data/datasets/CVPR23/train/'




