BATCH_SIZE = 32
LOSS = ""
LEARNING_RATE = 0.001
NO_EPOCHS = 50
DROPOUT = False
OPTIMIZER = "adam"
MODEL_BACKBONE= "resnet18"
MODEL_NAME = 'rn18fas'
ATTACK_TYPE = 'printing'

INFERENCE_DEVICE = 'CUDA'
TRAINING_DEVICE = 'CUDA'

TRAIN_DATASET = 'CVPR23'
TEST_DATASET = 'HAND_CRAWL'

PATH_TO_IMAGES = ''
PATH_TO_VIDEOS = ''
PATH_TO_SINGLE_VIDEO = ''
PATH_TO_TRAIN_DATASET = 'data/datasets/CVPR23/train/'

PATH_TO_FAS_MODEL = ''
PATH_TO_FD_MODEL =''



