channels:
- conda-forge
dependencies:
- python=3.11.4
- pip<=23.2.1
- pip:
  - mlflow==2.11.3
  - cloudpickle==3.0.0
  - numpy==1.25.2
  - packaging==23.1
  - psutil==5.9.5
  - pyyaml==6.0.1
  - scikit-learn==1.4.1.post1
  - scipy==1.12.0
name: mlflow-env
